const countries = [
  { code: "AF", name: "afghanistan" },
  { code: "AX", name: "aland islands" },
  { code: "AL", name: "albania" },
  { code: "DZ", name: "algeria" },
  { code: "AS", name: "american samoa" },
  { code: "AD", name: "andorra" },
  { code: "AO", name: "angola" },
  { code: "AI", name: "anguilla" },
  { code: "AQ", name: "antarctica" },
  { code: "AG", name: "antigua and barbuda" },
  { code: "AR", name: "argentina" },
  { code: "AM", name: "armenia" },
  { code: "AW", name: "aruba" },
  { code: "AU", name: "australia" },
  { code: "AT", name: "austria" },
  { code: "AZ", name: "azerbaijan" },
  { code: "BS", name: "bahamas" },
  { code: "BH", name: "bahrain" },
  { code: "BD", name: "bangladesh" },
  { code: "BB", name: "barbados" },
  { code: "BY", name: "belarus" },
  { code: "BE", name: "belgium" },
  { code: "BZ", name: "belize" },
  { code: "BJ", name: "benin" },
  { code: "BM", name: "bermuda" },
  { code: "BT", name: "bhutan" },
  { code: "BO", name: "bolivia" },
  { code: "BQ", name: "bonaire saint eustatius and saba" },
  { code: "BA", name: "bosnia and herzegovina" },
  { code: "BW", name: "botswana" },
  { code: "BV", name: "bouvet island" },
  { code: "BR", name: "brazil" },
  { code: "IO", name: "british indian ocean territory" },
  { code: "VG", name: "british virgin islands" },
  { code: "BN", name: "brunei" },
  { code: "BG", name: "bulgaria" },
  { code: "BF", name: "burkina faso" },
  { code: "BI", name: "burundi" },
  { code: "KH", name: "cambodia" },
  { code: "CM", name: "cameroon" },
  { code: "CA", name: "canada" },
  { code: "CV", name: "cape verde" },
  { code: "KY", name: "cayman islands" },
  { code: "CF", name: "central african republic" },
  { code: "TD", name: "chad" },
  { code: "CL", name: "chile" },
  { code: "CN", name: "china" },
  { code: "CX", name: "christmas island" },
  { code: "CC", name: "cocos islands" },
  { code: "CO", name: "colombia" },
  { code: "KM", name: "comoros" },
  { code: "CK", name: "cook islands" },
  { code: "CR", name: "costa rica" },
  { code: "HR", name: "croatia" },
  { code: "CU", name: "cuba" },
  { code: "CW", name: "curacao" },
  { code: "CY", name: "cyprus" },
  { code: "CZ", name: "czech republic" },
  { code: "CD", name: "democratic republic of the congo" },
  { code: "DK", name: "denmark" },
  { code: "DJ", name: "djibouti" },
  { code: "DM", name: "dominica" },
  { code: "DO", name: "dominican republic" },
  { code: "TL", name: "east timor" },
  { code: "EC", name: "ecuador" },
  { code: "EG", name: "egypt" },
  { code: "SV", name: "el salvador" },
  { code: "GQ", name: "equatorial guinea" },
  { code: "ER", name: "eritrea" },
  { code: "EE", name: "estonia" },
  { code: "ET", name: "ethiopia" },
  { code: "FK", name: "falkland islands" },
  { code: "FO", name: "faroe islands" },
  { code: "FJ", name: "fiji" },
  { code: "FI", name: "finland" },
  { code: "FR", name: "france" },
  { code: "GF", name: "french guiana" },
  { code: "PF", name: "french polynesia" },
  { code: "TF", name: "french southern territories" },
  { code: "GA", name: "gabon" },
  { code: "GM", name: "gambia" },
  { code: "GE", name: "georgia" },
  { code: "DE", name: "germany" },
  { code: "GH", name: "ghana" },
  { code: "GI", name: "gibraltar" },
  { code: "GR", name: "greece" },
  { code: "GL", name: "greenland" },
  { code: "GD", name: "grenada" },
  { code: "GP", name: "guadeloupe" },
  { code: "GU", name: "guam" },
  { code: "GT", name: "guatemala" },
  { code: "GG", name: "guernsey" },
  { code: "GN", name: "guinea" },
  { code: "GW", name: "guinea bissau" },
  { code: "GY", name: "guyana" },
  { code: "HT", name: "haiti" },
  { code: "HM", name: "heard island and mcdonald islands" },
  { code: "HN", name: "honduras" },
  { code: "HK", name: "hong kong" },
  { code: "HU", name: "hungary" },
  { code: "IS", name: "iceland" },
  { code: "IN", name: "india" },
  { code: "ID", name: "indonesia" },
  { code: "IR", name: "iran" },
  { code: "IQ", name: "iraq" },
  { code: "IE", name: "ireland" },
  { code: "IM", name: "isle of man" },
  { code: "IL", name: "israel" },
  { code: "IT", name: "italy" },
  { code: "CI", name: "ivory coast" },
  { code: "JM", name: "jamaica" },
  { code: "JP", name: "japan" },
  { code: "JE", name: "jersey" },
  { code: "JO", name: "jordan" },
  { code: "KZ", name: "kazakhstan" },
  { code: "KE", name: "kenya" },
  { code: "KI", name: "kiribati" },
  { code: "XK", name: "kosovo" },
  { code: "KW", name: "kuwait" },
  { code: "KG", name: "kyrgyzstan" },
  { code: "LA", name: "laos" },
  { code: "LV", name: "latvia" },
  { code: "LB", name: "lebanon" },
  { code: "LS", name: "lesotho" },
  { code: "LR", name: "liberia" },
  { code: "LY", name: "libya" },
  { code: "LI", name: "liechtenstein" },
  { code: "LT", name: "lithuania" },
  { code: "LU", name: "luxembourg" },
  { code: "MO", name: "macao" },
  { code: "MK", name: "macedonia" },
  { code: "MG", name: "madagascar" },
  { code: "MW", name: "malawi" },
  { code: "MY", name: "malaysia" },
  { code: "MV", name: "maldives" },
  { code: "ML", name: "mali" },
  { code: "MT", name: "malta" },
  { code: "MH", name: "marshall islands" },
  { code: "MQ", name: "martinique" },
  { code: "MR", name: "mauritania" },
  { code: "MU", name: "mauritius" },
  { code: "YT", name: "mayotte" },
  { code: "MX", name: "mexico" },
  { code: "FM", name: "micronesia" },
  { code: "MD", name: "moldova" },
  { code: "MC", name: "monaco" },
  { code: "MN", name: "mongolia" },
  { code: "ME", name: "montenegro" },
  { code: "MS", name: "montserrat" },
  { code: "MA", name: "morocco" },
  { code: "MZ", name: "mozambique" },
  { code: "MM", name: "myanmar" },
  { code: "NA", name: "namibia" },
  { code: "NR", name: "nauru" },
  { code: "NP", name: "nepal" },
  { code: "NL", name: "netherlands" },
  { code: "NC", name: "new caledonia" },
  { code: "NZ", name: "new zealand" },
  { code: "NI", name: "nicaragua" },
  { code: "NE", name: "niger" },
  { code: "NG", name: "nigeria" },
  { code: "NU", name: "niue" },
  { code: "NF", name: "norfolk island" },
  { code: "KP", name: "north korea" },
  { code: "MP", name: "northern mariana islands" },
  { code: "NO", name: "norway" },
  { code: "OM", name: "oman" },
  { code: "PK", name: "pakistan" },
  { code: "PW", name: "palau" },
  { code: "PS", name: "palestinian territory" },
  { code: "PA", name: "panama" },
  { code: "PG", name: "papua new guinea" },
  { code: "PY", name: "paraguay" },
  { code: "PE", name: "peru" },
  { code: "PH", name: "philippines" },
  { code: "PN", name: "pitcairn" },
  { code: "PL", name: "poland" },
  { code: "PT", name: "portugal" },
  { code: "PR", name: "puerto rico" },
  { code: "QA", name: "qatar" },
  { code: "CG", name: "republic of the congo" },
  { code: "RE", name: "reunion" },
  { code: "RO", name: "romania" },
  { code: "RU", name: "russia" },
  { code: "RW", name: "rwanda" },
  { code: "BL", name: "saint barthelemy" },
  { code: "SH", name: "saint helena" },
  { code: "KN", name: "saint kitts and nevis" },
  { code: "LC", name: "saint lucia" },
  { code: "MF", name: "saint martin" },
  { code: "PM", name: "saint pierre and miquelon" },
  { code: "VC", name: "saint vincent and the grenadines" },
  { code: "WS", name: "samoa" },
  { code: "SM", name: "san marino" },
  { code: "ST", name: "sao tome and principe" },
  { code: "SA", name: "saudi arabia" },
  { code: "SN", name: "senegal" },
  { code: "RS", name: "serbia" },
  { code: "SC", name: "seychelles" },
  { code: "SL", name: "sierra leone" },
  { code: "SG", name: "singapore" },
  { code: "SX", name: "sint maarten" },
  { code: "SK", name: "slovakia" },
  { code: "SI", name: "slovenia" },
  { code: "SB", name: "solomon islands" },
  { code: "SO", name: "somalia" },
  { code: "ZA", name: "south africa" },
  { code: "GS", name: "south georgia and the south sandwich islands" },
  { code: "KR", name: "south korea" },
  { code: "SS", name: "south sudan" },
  { code: "ES", name: "spain" },
  { code: "LK", name: "sri lanka" },
  { code: "SD", name: "sudan" },
  { code: "SR", name: "suriname" },
  { code: "SJ", name: "svalbard and jan mayen" },
  { code: "SZ", name: "swaziland" },
  { code: "SE", name: "sweden" },
  { code: "CH", name: "switzerland" },
  { code: "SY", name: "syria" },
  { code: "TW", name: "taiwan" },
  { code: "TJ", name: "tajikistan" },
  { code: "TZ", name: "tanzania" },
  { code: "TH", name: "thailand" },
  { code: "TG", name: "togo" },
  { code: "TK", name: "tokelau" },
  { code: "TO", name: "tonga" },
  { code: "TT", name: "trinidad and tobago" },
  { code: "TN", name: "tunisia" },
  { code: "TR", name: "turkey" },
  { code: "TM", name: "turkmenistan" },
  { code: "TC", name: "turks and caicos islands" },
  { code: "TV", name: "tuvalu" },
  { code: "UG", name: "uganda" },
  { code: "UA", name: "ukraine" },
  { code: "AE", name: "united arab emirates" },
  { code: "GB", name: "united kingdom" },
  { code: "US", name: "united states" },
  { code: "UM", name: "united states minor outlying islands" },
  { code: "UY", name: "uruguay" },
  { code: "VI", name: "us virgin islands" },
  { code: "UZ", name: "uzbekistan" },
  { code: "VU", name: "vanuatu" },
  { code: "VA", name: "vatican" },
  { code: "VE", name: "venezuela" },
  { code: "VN", name: "vietnam" },
  { code: "WF", name: "wallis and futuna" },
  { code: "EH", name: "western sahara" },
  { code: "YE", name: "yemen" },
  { code: "ZM", name: "zambia" },
  { code: "ZW", name: "zimbabwe" },
];

export default countries;
